### ISSUE TITLE
Using helm, mastodon(web, streaming, sidekiq) is not installed. Only postgreSQL, redis are installed.

### ISSUE THREAD

**Issue by choigonyok** [mastodon/chart#130]
I use Helm chart to deploy Mastodon in my VM kubernetes cluster.

But only PostgreSQL, Redis is installed When I deploy Mastodon, PostgreSQL and Redis.

Idk what is the problem.

Anyone knows about this issue?

Below, I attached my valuse.yaml file. and I use `helm install --namespace mastodon --create-namespace --debug my-mastodon ./ -f values.yaml`

<details><summary>Details</summary>
<p>

```
image:
  repository: ghcr.io/mastodon/mastodon
  tag: "v4.0"
  pullPolicy: IfNotPresent

mastodon:
  labels: {}

  createAdmin:
    enabled: true
    username: admin
    email: admin@slexn.com
  hooks:
    dbMigrate:
      enabled: true
    assetsPrecompile:
      enabled: true
  cron:
    removeMedia:
      enabled: true
      schedule: "0 0 * * 0"
  locale: en
  local_domain: mastodon.local
  web_domain: null
  singleUserMode: false
  authorizedFetch: false
  limitedFederationMode: false
  persistence:
    assets:
      accessMode: ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
    system:
      accessMode: ReadWriteOnce
      resources:
        requests:
          storage: 100Gi
  s3:
    enabled: false
    access_key: ""
    access_secret: ""
    existingSecret: ""
    bucket: ""
    endpoint: ""
    hostname: ""
    region: ""
    permission: ""
    alias_host: ""
  deepl:
    enabled: false
    plan:
    apiKeySecretRef:
      name:
      key:
  hcaptcha:
    enabled: false
    siteId:
    secretKeySecretRef:
      name:
      key:
  secrets:
    secret_key_base: "f704da41ee039045aa267653d2954db0d4283a9f63ac60e445851cb2354a633372446ffa66f86aff56570c9d24fb77958c32c7bb269edb0b3a56060ba98d9fb1"
    otp_secret: "1b325bdca9099f38f79a95a12b2a35bca184910836cb2ecfb6beee58a9de85c044f6439e1d545c4c11f107c706507051f793119106e5a2a327974a50d244ed29"
    vapid:
      private_key: "vN24YYVW2f1k809AKtH9QoSHI2QmqRxXVIusBEO0tms="
      public_key: "BCyWPOsF5CmRqbzAZNEFiaY88dLThieRmRNXr8NbpypVCxPwf27VkAGgtgH234LMcjw9TT9PCZbUaNA3pDYatBs="
    existingSecret: ""

  revisionHistoryLimit: 2

  sidekiq:
    podSecurityContext: {}
    securityContext: {}
    resources: {}
    affinity: {}
    topologySpreadConstraints: {}
    workers:
      - name: all-queues
        concurrency: 25
        replicas: 1
        resources: {}
        affinity: {}
        topologySpreadConstraints: {}
        queues:
          - default,8
          - push,6
          - ingress,4
          - mailers,2
          - pull
          - scheduler
        image:
          repository:
          tag:
        customDatabaseConfigYml:
          configMapRef:
            name:
            key:
  smtp:
    domain: localhost
    server: smtp.mailplug.co.kr
    from_address: notify3@slexn.com
    auth_method: plain
    delivery_method: smtp
    enable_starttls: false
    openssl_verify_mode: none
    port: 465
    tls: false
    login: notify3@slexn.com
    password: Snix2019!
    existingSecret:
  streaming:
    image:
      repository:
      tag:
    port: 4000
    workers: 1
    base_url: null
    replicas: 1
    affinity: {}
    topologySpreadConstraints: {}
    podSecurityContext: {}
    securityContext: {}
    resources: {}
  web:
    port: 3000
    replicas: 1
    affinity: {}
    topologySpreadConstraints: {}
    podSecurityContext: {}
    securityContext: {}
    resources: {}
    minThreads: "5"
    maxThreads: "5"
    workers: "2"
    persistentTimeout: "20"
    image:
      repository:
      tag:
    customDatabaseConfigYml:
      configMapRef:
        name:
        key:

  cacheBuster:
    enabled: false
    httpMethod: "GET"
    authHeader:
    authToken:
      existingSecret:

  metrics:
    statsd:
      address: ""
      exporter:
        enabled: false
        port: 9102

  preparedStatements: true

  extraEnvVars: {}

ingress:
  enabled: false
  annotations:
  ingressClassName:
  hosts:
    - host: mastodon.local
      paths:
        - path: "/"
  tls:
    - secretName: mastodon-tls
      hosts:
        - mastodon.local

  streaming:
    enabled: false
    annotations:
    ingressClassName:
    hosts:
      - host: streaming.mastodon.local
        paths:
          - path: "/"
    tls:
      - secretName: mastodon-tls
        hosts:
          - streaming.mastodon.local

elasticsearch:
  enabled: false
  image:
    tag: 7

postgresql:
  enabled: true
  volumePermissions:
    enabled: true
  auth:
    database: mastodon_production
    username: mastodon
    password: "admin"
    existingSecret: ""
  readReplica:
    hostname:
    port:
    auth:
      database:
      username:
      password:
      existingSecret:

redis:
  enabled: true
  volumePermissions:
    enabled: true
  hostname: "my-mastodon-redis-master.mastodon.svc.cluster.local"
  port: 6379
  auth:
    password: "admin"
  replica:
    replicaCount: 0

service:
  type: ClusterIP
  port: 80

externalAuth:
  oidc:
    enabled: false
  saml:
    enabled: false
    omniauth_only: false
  cas:
    enabled: false
  pam:
    enabled: false
  ldap:
    enabled: false

podSecurityContext:
  runAsUser: 991
  runAsGroup: 991
  fsGroup: 991

securityContext: {}

serviceAccount:
  create: true
  annotations: {}
  name: "mastodon-sa"

deploymentAnnotations: {}

podAnnotations: {}

revisionPodAnnotation: true

jobAnnotations: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

topologySpreadConstraints: {}

volumeMounts: []

volumes: []
```

</p>
</details>
