### ISSUE TITLE
mastodon-web still looks for secret mastodon-postgresql even when existing secret is used

### ISSUE THREAD

**Issue by ZeroEcks** [mastodon/chart#15]
When starting mastodon web I get 

`Warning  Failed     11s (x2 over 13s)  kubelet            Error: secret "mastodon-postgresql" not found`

However postgres can start and uses the correct key

` POSTGRES_POSTGRES_PASSWORD:           <set to the key 'postgres-password' in secret 'mastodon-values-secret'>  `

Seems theres some kind of mistake in the handling code for this?

My values.yaml contains

```
    postgresql:
      # -- disable if you want to use an existing db; in which case the values below
      # must match those of that external postgres instance
      enabled: true
      # postgresqlHostname: preexisting-postgresql
      # postgresqlPort: 5432
      auth:
        database: mastodon_production
        username: mastodon
        # you must set a password; the password generated by the postgresql chart will
        # be rotated on each upgrade:
        # https://github.com/bitnami/charts/tree/master/bitnami/postgresql#upgrade
        password: ""
        # Set the password for the "postgres" admin user
        # set this to the same value as above if you've previously installed
        # this chart and you're having problems getting mastodon to connect to the DB
        postgresPassword: ""
        # you can also specify the name of an existing Secret
        # with a key of password set to the password you want
        existingSecret: "mastodon-values-secret"
   ```
