### ISSUE TITLE
depend on a pg operator instead?

### ISSUE THREAD

**Issue by KlavsKlavsen** [mastodon/chart#4]
I would recommend depending on a postgres operator - like https://github.com/zalando/postgres-operator - that will enable you to easily have DB backups, and DB scaling / HA managed by the operator (and the mastodon chart can then just define a pg instance per the operators CRD) - and it would be much easier to start getting horizontal scaling working with Mastodon.

**Comment by deepy** [comment]
Using the pg operator instead of the bitnami postgres subchart is perfectly possible, just set `enabled: false` and use `existingSecret` :-)

I'm using the zalando postgres operator for my cluster, but I wouldn't recommend bundling it with this chart as the documentation is sparse and support can be pretty slow

**Comment by KlavsKlavsen** [comment]
Still its a better option IMHO  and should be mentionened - and yeah - with open source I would not expect much in way of support - except perhaps a community somewhere to talk to :)

**Comment by SISheogorath** [comment]
As someone who currently uses and has previously built helm charts with the zalando postgres operator: I would stick with the bitnami charts as depenency. It's less complex from a technological perspective, and one who can debug helm, can debug this as well, and most important it allows to install the chart without special privileges.

While the operator once installed also works for namespace admins, one still needs to install it, and this might not always be possible.

**Comment by KlavsKlavsen** [comment]
I would just add this to templates - and add option to choose which.

Below template - and could then in future be adjusted to enable HA or other features for scaling mastodon - making it much easier for the user to get a scalable setup from this chart (if they want it).

```
 apiVersion: "acid.zalan.do/v1"
 kind: postgresql
 metadata:
   name: mastodon-pgsql
   namespace: {{ .Release.Namespace }}
 spec:
   teamId: mastodon
   volume:
     size: {{ .Values.postgresql.size }}
     {{- if .Values.postgresql.storageClass }}
     storageClass: {{ .Values.postgresql.storageClass }}
     {{- end }}
   numberOfInstances: 1
   users:
     mastodon_admin:
       - superuser
       - createdb
   databases:
     mastodon: mastodon_admin
   postgresql:
     version: "14"
   enableMasterLoadBalancer: false
```
