### ISSUE TITLE
Upgrade Redis ?

### ISSUE THREAD

**Issue by bocan** [mastodon/chart#57]
Something I've been wondering for a long while now.  Why is this chart still using Redis 6?

Redis 7 is used in the docker-compose.yaml file and I'm running Redis 7 without any obvious issue in my own chart/cluster - so - is there some reason it's set to such an old version in Chart.yaml?

It just needs something like so:

``` patch
diff --git a/Chart.lock b/Chart.lock
index 961e4fa..c0cdc69 100644
--- a/Chart.lock
+++ b/Chart.lock
@@ -7,6 +7,6 @@ dependencies:
   version: 11.1.3
 - name: redis
   repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
-  version: 16.13.2
-digest: sha256:17ea58a3264aa22faff18215c4269f47dabae956d0df273c684972f356416193
-generated: "2022-08-08T21:44:18.0195364+02:00"
+  version: 17.7.6
+digest: sha256:1a9598fa8e475adb9a9ed05f9d8aa37366895165f4cb3d861dd1483f6c7dc8c2
+generated: "2023-03-07T11:21:33.592016Z"
diff --git a/Chart.yaml b/Chart.yaml
index 1ebc973..f0eb034 100644
--- a/Chart.yaml
+++ b/Chart.yaml
@@ -32,6 +32,6 @@ dependencies:
     repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
     condition: postgresql.enabled
   - name: redis
-    version: 16.13.2
+    version: 17.7.6
     repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
     condition: redis.enabled
```

**Comment by bocan** [comment]
Blimey.  17.8.3 (Redis 7.0.9) has come out since, so it's even beyond what I run.

**Comment by jessebot** [comment]
I agree on updating all the subcharts to be the latest OCI compliant bitnami images. I've tested these and they work fine:

```yaml
  - name: postgresql
    version: 12.6.0
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
  - name: elasticsearch
    version: 19.10.1
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: elasticsearch.enabled
  - name: redis
    version: 17.11.6
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: redis.enabled
```

Perhaps enabling [renovate](https://github.com/renovatebot/renovate) to help keep the dependency charts up to date is good idea? Dependabot unfortunately doesn't work for helm charts themselves yet (it only works to update the docker image tags within helm charts right now).
